import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FIreFliesBackground from "@/components/FIreFliesBackground";
import Sound from "@/components/Sound";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Ye Myat Hein",
  description: "Generated by Ye Myat Hein",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground")}>
        {children}
        <FIreFliesBackground/>
        <Sound/>
      </body>
    </html>
  );
}
